name: CD to Kubernetes

on:
  workflow_run:
    workflows: [Build and Push Docker Image to ACR]
    types:
      - completed

jobs:
 
  Push-to-Kubernetes:
    runs-on: ubuntu-latest
    #needs: "Build and Push Docker Image to ACR"  # This step depends on the 'build' job

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'v1.30.0'  # Specify your Kubernetes version
    
    - name: Output deployment message
      run: |
        echo "$(kubectl version)"
    
    - name: Set up Kubernetes Kubeconfig
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      run: |
        mkdir -p ~/.kube
        echo "$KUBE_CONFIG_DATA" > ~/.kube/config
    
    - name: Set Kubernetes context to dev namespace
      run: |
        kubectl config set-context --current --namespace=dev

    - name: Update Kubernetes Deployments
      run: |
        kubectl set image deployment/dev-ui ui=${{ secrets.ACR_NAME }}.azurecr.io/${{ secrets.IMAGE_NAME }}:latest
        kubectl rollout status deployment/dev-ui
    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get deployment dev-ui